# Generated by Django 5.2.3 on 2025-06-27 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.kategorisupplier'),
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembayaran', models.DateField(auto_now_add=True)),
                ('jumlah_dibayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metode', models.CharField(choices=[('transfer', 'Transfer Bank'), ('cash', 'Cash'), ('ewallet', 'E-Wallet')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('lunas', 'Lunas'), ('gagal', 'Gagal')], max_length=20)),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.penjualan')),
            ],
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengiriman', models.DateField()),
                ('kurir', models.CharField(max_length=100)),
                ('nomor_resi', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('diproses', 'Diproses'), ('dikirim', 'Dikirim'), ('diterima', 'Diterima'), ('dibatalkan', 'Dibatalkan')], max_length=50)),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.penjualan')),
            ],
        ),
        migrations.CreateModel(
            name='PenyesuaianStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_perubahan', models.IntegerField(help_text='Isi positif untuk penambahan, negatif untuk pengurangan')),
                ('alasan', models.CharField(max_length=100)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.produk')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
